language: node_js
node_js:
    - "node"
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt init:dev
after_success:
  - cat ./spec/coverage/reports/lcov.info | ./node_modules/.bin/coveralls --verbose
